<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>opd</string>
	</array>
	<key>name</key>
	<string>OPDebugger</string>
	<key>patterns</key>
	<array>		
		<dict>
			<key>match</key>
			<string>(\d)+</string>
			<key>name</key>
			<string>constant.numeric.OPD</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Test</string>
			<key>name</key>
			<string>storage.type.OPD</string>
		</dict>
		<dict>
			<key>match</key>
			<string>returncode</string>
			<key>name</key>
			<string>storage.type.OPD</string>
		</dict>
		<!-- <dict>
			<key>begin</key>
			<string>===Test( )+(\d)+( )+===</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>warning</string>
				</dict>
			</dict>
			<key>end</key>
			<string>===finished with exit code -(\d)+ ===</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>warning</string>
				</dict>
			</dict>
		</dict> -->
	</array>
	<key>scopeName</key>
	<string>source.OPDebugger</string>
	<key>uuid</key>
	<string>uhuhuhu</string>
</dict>
</plist>